//! The one recipe a debug build adds to the catalogue: `mixengine-testkit`'s `fakeservice`.
//!
//! **Why a shipped crate carries a fixture's recipe at all.** Everything the daemon supervises comes
//! from a [`Recipe`], and every real one is a later roadmap task against a real server — Caddy is
//! T31, MariaDB T33. Until one lands there is no service a *real* `mixengined` process can be told
//! to run, and the tests that need one are exactly the tests that cannot be written any other way:
//! `mix service start` over a socket, a killed daemon adopting what outlived it, a log stream from a
//! process that is still talking. Those drive the binary that is built, so a fixture inside a test
//! module is unreachable from them.
//!
//! **What it replaces is strictly wider.** Until T30 this was `MIXENGINE_DEV_SPECS`: a path to a
//! JSON file of `ServiceSpec`s, which is a supervisor that runs whatever program a variable points
//! at, with whatever arguments and whatever environment. This runs one program — the `fakeservice`
//! inside the package a `packages` row names — with the flags below and nothing else. It is also the
//! *real* path: a test that declares one of these exercises the merge, the render, the diff, the
//! staging and the spec build, where a spec read from a file exercised none of them.
//!
//! Gated on `debug_assertions` all the same, because a release build has no business knowing about
//! this program, and because a home that somehow held a `fakeservice` row should be told plainly
//! that nothing can run it rather than quietly running one.

use std::path::PathBuf;

use mixengine_core::Result;
use mixengine_core::generate::{Context, Instancing, Preset, Recipe, Setting, TemplateFile};
use mixengine_proto::{
    Millis, ReadyCheck, ReloadBehaviour, RestartPolicy, ServiceSpec, ServiceSpecBuilder,
    StopBehaviour,
};

/// What `fakeservice` prints when it considers itself ready.
///
/// `mixengine_testkit::service::READY_LINE`, spelled again because this crate may not depend on the
/// testkit outside its own tests — that is the rule that keeps a fixture out of a shipped binary,
/// and it applies to this file too. The two are pinned together by the suites that start one of
/// these for real — `crates/mixengine-cli/tests/service.rs` above all — which wait for readiness and
/// therefore fail if the two strings ever drift apart.
const READY_LINE: &str = "fakeservice: ready";

/// The file this renders, and what a spec passes on the command line.
///
/// **The generated configuration is load-bearing rather than decorative**, which is the point of
/// rendering one at all: `fakeservice` reads its extra arguments out of this file, so a test that
/// changes an override and starts the service again is a test of the whole chain — row, merge,
/// template, diff, install, and a process that behaves differently because of it.
const ARGUMENTS_FILE: &str = "fakeservice.args";

/// What the reload command creates, inside the service's own configuration directory.
///
/// **A fixture's reload is the command running and nothing more**, which is exactly as much as a
/// real one is from the supervisor's side: `caddy reload` is a program the recipe names, run in the
/// service's surroundings, and whether the server then re-reads anything is the server's business.
/// So this one creates a file — the same `--touch` that makes a `StopBehaviour::Command` provable —
/// and a suite that changes an override on a *running* service looks for it.
const RELOADED_FILE: &str = "reloaded";

/// How long that command is given. Generous for what it does, and for the same reason every other
/// deadline in this file is: a first run of a freshly written executable on a Windows runner is a
/// virus scan before it is a process.
const RELOAD_PATIENCE: Millis = Millis(20_000);

/// One argument per line, blanks and `#` comments ignored by the reader.
///
/// Written with Jinja's whitespace control (`{%- -%}`) so that a flag nobody asked for leaves no
/// blank line behind: the point of the diff in `document::install` is that two renderings of the
/// same state are byte-identical, and a template that emits stray whitespace makes that harder to
/// reason about, not easier.
const ARGUMENTS: &str = "\
# Generated by MixEngine for {{ service.id }}; every edit here is overwritten.
{% if settings.never_ready -%}
--never-ready
{% elif settings.ready_after -%}
--ready-after
{{ settings.ready_after }}
{% endif -%}
{% if settings.log_every -%}
--log-every
{{ settings.log_every }}
{% endif -%}
{% if settings.eat_memory_mb -%}
--eat-memory-mb
{{ settings.eat_memory_mb }}
{% endif -%}
{% if settings.exit_after -%}
--exit-after
{{ settings.exit_after }}
--exit-code
{{ settings.exit_code }}
{% endif -%}
{% if settings.ignore_stop -%}
--ignore-stop
{% endif -%}
{{ extra }}";

/// Take this long to announce readiness, in milliseconds.
const READY_AFTER: &str = "ready_after";

/// Never announce readiness at all.
const NEVER_READY: &str = "never_ready";

/// How long the supervisor waits for readiness, in milliseconds.
const READY_TIMEOUT: &str = "ready_timeout_ms";

/// Print a line this often, in milliseconds. Zero is silence after the ready line.
const LOG_EVERY: &str = "log_every";

/// Take another bite of memory this big, in megabytes, every 50 ms. Zero is a service that eats
/// nothing — roadmap task **T68**, where a service is walked into a real ceiling.
const EAT_MEMORY_MB: &str = "eat_memory_mb";

/// Exit on its own after this long, in milliseconds. Zero is never.
const EXIT_AFTER: &str = "exit_after";

/// What to exit with when [`EXIT_AFTER`] arrives.
const EXIT_CODE: &str = "exit_code";

/// Install the stop handlers and then ignore them, so only a kill ends it.
const IGNORE_STOP: &str = "ignore_stop";

/// How long a stop is given before it becomes a kill, in milliseconds.
const STOP_GRACE: &str = "stop_grace_ms";

/// The services this one is to be started after.
const DEPENDS_ON: &str = "depends_on";

/// A `fakeservice` instance, configured by overrides.
#[derive(Debug)]
pub(crate) struct Fakeservice;

impl Recipe for Fakeservice {
    fn package(&self) -> &'static str {
        "fakeservice"
    }

    /// As many as a suite names. Half of what this fixture is for is a home holding several
    /// services that depend on each other, and one instance could not show that.
    fn instancing(&self) -> Instancing {
        Instancing::Named
    }

    /// A number well clear of anything a developer's machine runs, because these are fixtures.
    ///
    /// It exists so that the allocation T34c added is exercised by every suite that declares a
    /// service rather than only by the two databases: a second `fakeservice@…` gets the next port
    /// up, which is the same rule `mariadb@legacy` meets. Nothing here ever binds it.
    fn preferred_port(&self) -> Option<u16> {
        Some(41000)
    }

    /// Measured on the port above, so that the idle machinery T69 built has a fixture to run
    /// against.
    ///
    /// Nothing binds that port, which is exactly right for what the suites need: a `fakeservice`
    /// nobody connects to reads as idle, and a test that wants it busy connects to it.
    fn idle_probe(&self, context: &Context) -> Option<mixengine_proto::IdleProbe> {
        context
            .port()
            .map(|port| mixengine_proto::IdleProbe::Connections { port })
    }

    fn settings(&self) -> &'static [Setting] {
        &[
            Setting {
                key: DEPENDS_ON,
                default: Preset::List(&[]),
            },
            Setting {
                key: EXIT_AFTER,
                default: Preset::Number(0),
            },
            Setting {
                key: EXIT_CODE,
                default: Preset::Number(0),
            },
            Setting {
                key: IGNORE_STOP,
                default: Preset::Flag(false),
            },
            Setting {
                key: EAT_MEMORY_MB,
                default: Preset::Number(0),
            },
            Setting {
                key: LOG_EVERY,
                default: Preset::Number(0),
            },
            Setting {
                key: NEVER_READY,
                default: Preset::Flag(false),
            },
            Setting {
                key: READY_AFTER,
                default: Preset::Number(0),
            },
            Setting {
                // Twenty seconds, which is what every fixture spec in this workspace used before
                // there was a recipe: starting a process on a loaded Windows runner is measured in
                // seconds, and a test that means to wait one out says so with its own override.
                key: READY_TIMEOUT,
                default: Preset::Number(20_000),
            },
            Setting {
                key: STOP_GRACE,
                default: Preset::Number(500),
            },
        ]
    }

    fn files(&self) -> &'static [TemplateFile] {
        &[TemplateFile {
            path: ARGUMENTS_FILE,
            source: ARGUMENTS,
        }]
    }

    fn spec(&self, context: &Context) -> Result<ServiceSpecBuilder> {
        let settings = context.settings();

        // The binary is found through the `packages` row rather than named here: `install_path`
        // plus the package's own name, which is how every real recipe will find its server too.
        let program = context.program(context.package());

        let mut builder = ServiceSpec::builder(context.service().clone(), &program)
            .arg("--args-file")
            .arg(path(context.config(ARGUMENTS_FILE)))
            .cwd(context.etc())
            .ready(ReadyCheck::LogPattern {
                regex: READY_LINE.to_owned(),
                timeout: millis(settings.number(READY_TIMEOUT)),
            })
            // Nothing that declares one of these is about restarts, and a policy that put a service
            // back would turn a failing assertion into a test that takes a minute to fail.
            .restart(RestartPolicy::Never)
            .stop(StopBehaviour::Signal {
                grace: millis(settings.number(STOP_GRACE)),
            })
            .reload(ReloadBehaviour::Command {
                program,
                args: vec!["--touch".to_owned(), path(context.config(RELOADED_FILE))],
                patience: RELOAD_PATIENCE,
            });

        for dependency in settings.list(DEPENDS_ON) {
            // `Unrunnable` rather than `SettingType`, which is about a *shape*: this is a list of
            // strings, as declared, and one of the strings is not a service id. The `SpecError` it
            // carries says which and why, in the same words a spec that named one would produce.
            let id = mixengine_proto::ServiceId::parse(dependency.clone()).map_err(|source| {
                mixengine_core::Error::Unrunnable {
                    service: context.service().as_str().to_owned(),
                    source,
                }
            })?;

            builder = builder.depends_on(id);
        }

        Ok(builder)
    }
}

/// A path as an argument.
fn path(path: PathBuf) -> String {
    path.to_string_lossy().into_owned()
}

/// A setting as a length of time, with a negative one read as none at all.
fn millis(number: i64) -> Millis {
    Millis(u64::try_from(number).unwrap_or_default())
}
