// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * The account an apply's `CreateDatabase` step really used, after T202's free-name walk. Never a
 * password.
 */
export type AppliedDatabase = { 
/**
 * The server it lives on.
 */
service: ServiceId, 
/**
 * The database.
 */
database: string, 
/**
 * The account.
 */
user: string, };
