// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppliedDatabase } from "./AppliedDatabase";
import type { NextSteps } from "./NextSteps";
import type { StepOutcome } from "./StepOutcome";

/**
 * What an apply did, as the job's result — roadmap task **T78**.
 */
export type BlueprintApplied = { 
/**
 * Which blueprint, by slug.
 */
blueprint: string, 
/**
 * The project it made.
 */
project: string, 
/**
 * Where it lives.
 */
root: string, 
/**
 * One outcome per plan step, in the plan's own order.
 *
 * **Every step is here, including the ones that needed nothing**, because that is what makes a
 * resumed apply legible: a second run whose every line says *already true* is the proof that
 * the first one finished.
 */
steps: Array<StepOutcome>, 
/**
 * What is left to do, from the blueprint's `[[next_steps]]` — roadmap task **T205**, D6.
 */
next_steps?: NextSteps | null, 
/**
 * The account the database step really used, when there was one — T205, D6.
 */
database?: AppliedDatabase | null, };
