// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScaffoldConsent } from "./ScaffoldConsent";
import type { VersionAnswer } from "./VersionAnswer";

/**
 * `blueprint.apply` — what applying one would do, and doing it.
 */
export type BlueprintApply = { 
/**
 * Which blueprint, by slug.
 */
blueprint: string, 
/**
 * What the new project is called, and what `{project}` expands to.
 */
project: string, 
/**
 * Where it would live. Absolute; the client resolves it against its own current directory.
 */
root: string, 
/**
 * Whether [`root`](Self::root) is the project's directory or the place to make one in.
 *
 * `false` — the default, and what a path somebody typed means — takes `root` exactly as
 * spelled. A folder a person named is a folder a person named, and re-spelling it quietly
 * would be worse than the failure this field exists to answer.
 *
 * `true` says *make one under here*, and the daemon names it with the project's handle —
 * `domains::slug`, the rule `{project}` already expands through. **The naming happens at that
 * end and not in a client**, because a client may not hold that rule: `mix` cannot depend on
 * `mixengine-core` (`mixengine-proto/tests/workspace_layering.rs`), and the desktop
 * deliberately holds no naming rule at all. A client knows where it is standing; the daemon
 * knows what things are called.
 *
 * The composed path is not a surprise: it comes back in
 * [`PlanAction::RegisterProject`](crate::PlanAction), which every client renders before
 * anything is created.
 *
 * Roadmap task **T120a**.
 */
root_is_parent: boolean, 
/**
 * Whether to stop after planning.
 *
 * `true` answers [`BlueprintApplyResponse::Planned`](crate::BlueprintApplyResponse) and touches
 * nothing; `false` answers the job carrying the plan out. One method for both, because the plan
 * a person reads and the plan the daemon executes have to be the same list.
 */
dry_run: boolean, 
/**
 * Install what the plan's releases need of the machine before anything else — roadmap task
 * **T152**. What [`BlueprintApplyResponse::Planned`](crate::BlueprintApplyResponse)'s `needs`
 * asked about.
 */
install_prerequisites?: boolean, 
/**
 * Do not judge what the plan's releases need of the machine — T152. The smoke tests still run.
 */
ignore_requirements?: boolean, 
/**
 * The answers to the version questions this plan raises — roadmap task **T78**.
 *
 * **A question is asked by a client and answered in the request**, because a daemon has no
 * keyboard: a job that stopped halfway to ask one would be a job holding a project directory
 * hostage. An apply meeting a [`Disposition::Choice`](crate::Disposition) with no answer here
 * is refused before anything happens, naming every question it could not answer — and an
 * answer to a question this plan does not ask is refused too, because it is an answer composed
 * against a machine or a moment that has since changed.
 *
 * Defaulted, so a request written before this task still decodes.
 */
answers?: Array<VersionAnswer>, 
/**
 * Agreement to run the blueprint's own `[scaffold]` command — roadmap task **T78a**, its
 * design's D4.
 *
 * **Asked by a client and answered here**, exactly as a version mismatch is, and for the same
 * reason: a daemon has no keyboard, and a job that stopped halfway to ask would be a job
 * holding a project directory hostage.
 *
 * Absent, and the scaffold step ends `NotRun` while everything else is applied — a blueprint
 * must not become worthless because nobody answered one question. Present and disagreeing with
 * the plan, and the apply is refused before anything happens.
 */
scaffold?: ScaffoldConsent | null, 
/**
 * The `.env` keys the person agreed to have written, password included — roadmap task
 * **T205a**. Apart from [`BlueprintApply::scaffold`], since a plan can carry both and one
 * consent must not answer the other. A key the plan does not write is refused before
 * anything is touched.
 */
dotenv?: Array<string>, 
/**
 * Whether to plan a front end where this home has none — roadmap task **T115**.
 *
 * `core::sites` renders nothing for a home with no front end and succeeds while doing it, so a
 * manifest with a `[site]` applied to a fresh machine ends with a project, a database, a site
 * row, a domain, a certificate — and nothing listening.
 *
 * **Asked for rather than always.** An apply is about a project; provisioning the machine it
 * runs on is a wider thing, and doing it unasked would make every apply on a home with no web
 * server download one — including the ones deliberately about something else. The caller that
 * sets this is the one whose sentence is *get me a working site*.
 *
 * A home that has already chosen a front end — Nginx as much as Caddy — is left alone whatever
 * this says: the question is whether there is one at all, and a blueprint may not name which,
 * because exactly one runs per home and the choice is the home's.
 *
 * Defaulted, so a request written before this task still decodes and still means what it did.
 */
front_end: boolean, 
/**
 * Whether the services this apply **creates** start with the daemon — roadmap task **T116**.
 *
 * **Only what it creates.** A shared MariaDB somebody deliberately leaves stopped is not
 * something a second project gets to re-decide, so a step that plans
 * [`Satisfied`](crate::Disposition::Satisfied) is untouched — which also means a second apply
 * of the same blueprint sets nothing, and the flag is a statement about the machine this apply
 * is building rather than a repair of one it found.
 *
 * **Defaulted to `false`, and the default is a constraint rather than a taste.**
 * `crates/mixengine-cli/tests/warm_start.rs` is the `bench` job and times a single
 * `mix service start`; a fixture that quietly turned this on would put a boot walk beside that
 * measurement and make the number mean something else.
 */
autostart: boolean, };
