// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A runtime kind or a package an available list could not be read for — roadmap task **T196**.
 *
 * Said rather than left out in silence: a list with a kind missing and no word about it reads as
 * an index that publishes nothing for that kind, and sends a person looking for a version that
 * was never gone.
 */
export type CatalogueGap = { 
/**
 * The runtime kind or the package name.
 */
name: string, 
/**
 * Why, as the daemon's own sentence.
 */
reason: string, };
