// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashFrame } from "./CrashFrame";
import type { CrashLocation } from "./CrashLocation";
import type { DaemonVersion } from "./DaemonVersion";
import type { Timestamp } from "./Timestamp";

/**
 * One panic, as much of it as may travel.
 */
export type CrashReport = { 
/**
 * [`CRASH_FORMAT`].
 */
format: number, 
/**
 * When the hook ran, which is within microseconds of the panic.
 */
recorded_at: Timestamp, 
/**
 * What was running, and what it spoke.
 */
daemon: DaemonVersion, 
/**
 * `std::env::consts::OS`.
 */
os: string, 
/**
 * `std::env::consts::ARCH`.
 */
arch: string, 
/**
 * The panicking thread's name, or [`None`] when it had none.
 *
 * Every thread name reachable here is a literal from `std` or `tokio` — nothing in this
 * workspace names a thread — so this is one of the three safe kinds of field the module header
 * lists rather than an exception to them.
 */
thread?: string | null, 
/**
 * Where it was raised, or [`None`] when `std` reported none.
 */
location?: CrashLocation | null, 
/**
 * The backtrace, innermost first, as offsets into the executable.
 *
 * Empty in a format-1 report, whose names are in [`symbols`](Self::symbols), and when the
 * platform could not unwind — which leaves a location, still most of what a reader needs.
 */
frames: Array<CrashFrame>, 
/**
 * The backtrace as symbol names, where this build resolved them itself: a debug build, and
 * every format-1 report.
 *
 * **Symbol names and nothing else**: the `at <path>:<line>` lines a rendered backtrace carries
 * are the one place a build machine's directories appear, and they are dropped before a report
 * is built. A release build resolves nothing in the hook and leaves this empty. **Not paired
 * with [`frames`](Self::frames)**: the names come from `std`'s own capture, which starts in a
 * different frame.
 */
symbols?: Array<string>, 
/**
 * The executable's build identifier: the GNU build-id on Linux, `LC_UUID` on macOS, the
 * CodeView GUID and age on Windows. A symbol file is matched against it, so a report is never
 * read against the wrong build. [`None`] in a format-1 report, or when the platform could not
 * read one.
 */
build_id?: string | null, };
