// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One frame of the panicking thread, as a position in the executable.
 */
export type CrashFrame = { 
/**
 * The frame's return address minus the executable's base, as `0x…` hex: the same on every
 * machine that ran this build, whatever address-space randomisation chose. `scripts/symbolize.mjs`
 * turns it back into a name with the release's symbol file.
 *
 * [`None`] for a frame outside the executable — `libc`, `ntdll`, a system framework. Nothing
 * names the library it was in, because a module's name is a path on the machine.
 */
offset?: string | null, };
