// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialStore } from "./CredentialStore";

/**
 * What `daemon.set_credential_store` takes — roadmap task **T194**.
 */
export type CredentialStoreSet = { 
/**
 * The store the home should keep its passwords in from the next start.
 */
store: CredentialStore, };
