// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialStore } from "./CredentialStore";

/**
 * The store a daemon runs on, and whether it would accept a switch — roadmap task **T194**.
 */
export type CredentialsStatus = { 
/**
 * The store the running daemon built its host with.
 */
store: CredentialStore, 
/**
 * Whether `daemon.set_credential_store` would accept the other store. Decided by the daemon, so
 * no client repeats which system and which build may choose which: only a development build,
 * and a Linux release with no keyring, keep a file.
 */
choosable: boolean, };
