// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialStore } from "./CredentialStore";

/**
 * What `daemon.set_credential_store` answers — roadmap task **T194**.
 *
 * **Two stores, because a switch applies at the next start**: the running daemon keeps the host it
 * was built with, and a client says so when the two differ.
 */
export type CredentialStoreChange = { 
/**
 * What the home has recorded, and the next start will use.
 */
recorded: CredentialStore, 
/**
 * What this daemon is running on until it stops.
 */
running: CredentialStore, };
