// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which credential store a home keeps its passwords in — roadmap task **T194**,
 * [ADR 0059](../../../docs/decisions/0059-a-linux-release-may-keep-a-homes-credentials-in-a-file.md).
 */
export type CredentialStore = "os" | "home";
