// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialsStatus } from "./CredentialsStatus";
import type { DnsStatus } from "./DnsStatus";
import type { ElevationSummary } from "./ElevationSummary";
import type { ProtocolVersion } from "./ProtocolVersion";
import type { Timestamp } from "./Timestamp";
import type { UpdateOffer } from "./UpdateOffer";
import type { Uptime } from "./Uptime";

/**
 * Everything the daemon knows about itself, for `daemon.status`.
 *
 * Paths are strings and not `PathBuf`s. serde will refuse a `PathBuf` that is not valid UTF-8, and
 * a home directory with an unusual name is a reason to see it spelled oddly in `mix status`, not a
 * reason for `mix status` to fail. They are for reading; nothing joins or opens them.
 */
export type DaemonStatus = { 
/**
 * The daemon's build version — `CARGO_PKG_VERSION`, the same string `mixengined --version`
 * prints.
 */
version: string, 
/**
 * The API version this daemon speaks. A client compares it with its own
 * [`PROTOCOL_VERSION`](crate::PROTOCOL_VERSION) before it trusts anything else in this struct.
 */
protocol: ProtocolVersion, 
/**
 * The daemon's process id, so a user can find it in a task manager and a client can tell one
 * restart from another.
 */
pid: number, 
/**
 * `MIXENGINE_HOME` as it was resolved. The single most useful line when somebody is talking to
 * a daemon they did not expect to be talking to.
 */
home: string, 
/**
 * Where it listens: a socket path, or a named pipe.
 */
endpoint: string, 
/**
 * The SQLite file it opened. Not derivable from `home` — `[paths]` can move it.
 */
database: string, 
/**
 * When this daemon started.
 */
started_at: Timestamp, 
/**
 * How long ago that was, computed by the daemon rather than by the client.
 *
 * Redundant with [`DaemonStatus::started_at`] only if the two clocks agree, which is exactly
 * the assumption worth avoiding: a monotonic reading here means "up 3 days" stays right across
 * a system clock that was corrected while the daemon ran.
 */
uptime: Uptime, 
/**
 * What is waiting for permission, and whether this machine could ask for it, or [`None`] from a
 * daemon built before this member existed.
 *
 * **In the call every client already makes**, so `mix status` can say "3 operations are waiting
 * for permission" without a second round trip and without a client deciding what *degraded*
 * means — the T40b design, D6. The list itself is `elevation.status`, because that is a screen
 * and this is a status line.
 *
 * **Optional because it arrived after protocol 1 was frozen** —
 * [ADR 0019](../../../docs/decisions/0019-an-added-response-member-is-optional.md), roadmap
 * task **T88c**. It was required until then, which meant a `mix` from a new build could not
 * *decode* the answer of an older daemon that had not been restarted yet.
 *
 * **[`None`] means the daemon predates the member and nothing else.** It is never "the queue
 * could not be read": this call is fallible for exactly that case, so an unreadable queue is an
 * [`Error`] rather than a zero nobody established — which is the stale-clear failure D6 exists
 * to prevent, and the reason there is no `Default` for
 * [`ElevationSummary`](crate::ElevationSummary) here.
 */
elevation?: ElevationSummary | null, 
/**
 * Which of the two name mechanisms this home is running on, and why — roadmap task **T44** — or
 * [`None`] from a daemon built before this member existed.
 *
 * **In the call every client already makes**, on [`DaemonStatus::elevation`]'s reasoning: "is
 * `blog.test` going to resolve, and will a wildcard under it" is a status line, not a screen,
 * and a client that had to ask a second method for it would render the first line of `mix
 * status` a round trip late.
 *
 * **Optional on [`DaemonStatus::elevation`]'s reasoning too**, and for the same skew — **T88c**
 * changed both at once, because fixing one while the other was required bought nothing. [`None`]
 * means the daemon predates the member; a daemon that has it always answers [`Some`], since this
 * is read from state it owns and cannot fail.
 */
dns?: DnsStatus | null, 
/**
 * A release this daemon has been offered, or [`None`] — roadmap task **T88**.
 *
 * **In the call every client already makes**, on [`DaemonStatus::elevation`]'s reasoning: *"is
 * there a newer MixEngine"* is a status line and not a screen, and the screen is
 * `update.status`.
 *
 * **Optional because of what it means, and skew-tolerant as a consequence rather than as a
 * workaround.** [`None`] is the honest value for a daemon that has not checked yet, for one
 * whose check found nothing, and for one built before this member existed — three states a
 * client renders identically, which is *nothing at all*. This is the only member here whose
 * [`None`] carries more than the wire fact, and **T88c** — which made
 * [`DaemonStatus::elevation`] and [`DaemonStatus::dns`] optional as well, under
 * [ADR 0019](../../../docs/decisions/0019-an-added-response-member-is-optional.md) — left it
 * exactly as it was.
 */
update?: UpdateOffer | null, 
/**
 * Which credential store this home keeps its passwords in — roadmap task **T194** — or
 * [`None`] from a daemon built before this member existed.
 *
 * **In the call every client already makes**, on [`DaemonStatus::elevation`]'s reasoning: where
 * the passwords are is a status line, and the switch that changes it is
 * `daemon.set_credential_store`.
 */
credentials?: CredentialsStatus | null, };
