// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredSiteState } from "./DeclaredSiteState";

/**
 * One site a project's `mixengine.toml` declares, and whether this home has it — roadmap task
 * **T204**, spec D7.
 */
export type DeclaredSite = { 
/**
 * The entry's `domain`, or `<slug>.test` for one that names none — the name `site.create`
 * would give it, and the one `from` answers to.
 */
domain: string, 
/**
 * Every other name it answers to.
 */
aliases: Array<string>, 
/**
 * Whether a site here holds it, and whose.
 */
state: DeclaredSiteState, };
