// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a declared site is here — spec D7.
 */
export type DeclaredSiteState = { "is": "here" } | { "is": "missing" } | { "is": "elsewhere", 
/**
 * That project's name, or that extension's id.
 */
owner: string, };
