// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`HealthCheck`] asks.
 *
 * Deliberately not [`ReadyCheck`]: two of those variants only make sense once. `LogPattern` matches
 * a line printed during startup and would never match again, and `PidAlive` asks something the
 * supervisor already knows without probing — a health check that cannot fail is worse than none,
 * because it reports health it never measured.
 */
export type HealthProbe = { "type": "tcp", 
/**
 * Where to connect.
 */
addr: string, } | { "type": "unix_socket", 
/**
 * The socket path.
 */
path: string, } | { "type": "http", 
/**
 * The URL to request.
 */
url: string, 
/**
 * The status that means healthy.
 */
expect_status: number, } | { "type": "mysql_greeting", 
/**
 * Where the server listens.
 */
addr: string, } | { "type": "redis_ping", 
/**
 * Where the server listens.
 */
addr: string, } | { "type": "command", 
/**
 * The program to run.
 */
program: string, 
/**
 * Its arguments.
 */
args: Array<string>, };
