// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviousCopy } from "./PreviousCopy";

/**
 * What `home.previous` answers.
 */
export type HomePrevious = { 
/**
 * The newest copy in a kept folder, while this home has nothing of its own yet; absent
 * otherwise.
 */
copy?: PreviousCopy | null, };
