// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `home.restore` did.
 */
export type HomeRestoreReport = { 
/**
 * Projects restored.
 */
projects: number, 
/**
 * Sites restored.
 */
sites: number, 
/**
 * Services restored, each left stopped.
 */
services: number, 
/**
 * Runtime rows restored (not counting ones this home already had).
 */
runtimes: number, 
/**
 * Package rows restored.
 */
packages: number, 
/**
 * What the copy held and this home could not take, one phrase each.
 */
skipped: Array<string>, 
/**
 * Steps after the restore that did not finish — a password, the hosts file, a certificate —
 * one sentence each with what to do. The restore itself stands.
 */
problems: Array<string>, };
