// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsMinute } from "./MetricsMinute";

/**
 * The rows a [`MetricsHistoryQuery`] found, oldest first.
 */
export type MetricsHistory = { 
/**
 * The rows, ordered by minute and then by subject.
 *
 * **A minute with no row for a subject is a minute nobody measured** — the service was stopped,
 * or the machine was asleep, or the daemon was being replaced. It is never a minute in which
 * nothing was used, so a client draws a gap rather than joining the points across it.
 */
minutes: Array<MetricsMinute>, 
/**
 * How long this home keeps a row, so a client can say why its chart starts where it does.
 */
retention_hours: number, 
/**
 * How many logical processors this machine has — roadmap task **T190c**, and
 * [`MetricsFrame::cores`]'s reason: what `cpu_avg` and `cpu_peak` are divided by to be drawn
 * as a share of the machine. The rows themselves stay in percent of one core.
 */
cores: number, };
