// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSample } from "./MetricsSample";
import type { Timestamp } from "./Timestamp";

/**
 * Every subject that could be measured, in one pass.
 *
 * **The moment belongs to the frame and not to the sample.** One refresh produced all of these, so
 * a timestamp repeated once per service would be a value free to disagree with itself the day
 * somebody assembled a frame out of two readings.
 */
export type MetricsFrame = { 
/**
 * When the pass was taken.
 */
at: Timestamp, 
/**
 * One per subject that could be measured. **A subject that could not is absent** — never a
 * sample of zero, because *not measured* and *measured nothing* are different facts.
 */
samples: Array<MetricsSample>, 
/**
 * How many logical processors this machine has — roadmap task **T190c**.
 *
 * What a client divides [`MetricsSample::cpu_percent`] by to show a share of the whole
 * machine, as Task Manager does. The same count as
 * [`LimitSupport::cores`](crate::LimitSupport). A frame from a daemon older than this field
 * reads as `1`, which is the unit it was always in.
 */
cores: number, };
