// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSubject } from "./MetricsSubject";

/**
 * One subject's reading, taken as part of a [`MetricsFrame`].
 */
export type MetricsSample = { 
/**
 * Whose reading this is.
 */
subject: MetricsSubject, 
/**
 * Percentage of **one** core, so 250 is two and a half cores' worth.
 *
 * The unit [`ResourceLimits::cpu_percent`](crate::ResourceLimits) is declared in, deliberately:
 * a client that offers a cap and then draws the usage never converts between the two.
 *
 * [`None`] where no figure could be taken, and **never `0.0` for that case** — a CPU reading is
 * a difference between two moments, and the first reading of a group has nothing to subtract
 * from. A zero there would draw an idle service during the second it is most expensive.
 *
 * **On the stream and in a snapshot it is the mean of the last five seconds of readings**
 * (roadmap task T190c), because one second of CPU time on Windows is a count of 15.6 ms
 * quanta. The minute history is kept from the readings themselves.
 */
cpu_percent: number | null, 
/**
 * Resident bytes over the whole group, with shared pages counted once per process.
 *
 * **Not the quantity a `memory_mb` limit is judged against** — see
 * [`MemoryMeasure`](crate::MemoryMeasure), which is commit charge on Windows and charged pages
 * on Linux. A client rendering this and a limit as one ratio is rendering two different
 * measurements as though they were one.
 */
rss_bytes: number, 
/**
 * How many processes the group holds, the root included.
 */
processes: number, };
