// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextStepKind } from "./NextStepKind";

/**
 * One thing a blueprint says is left to do — roadmap task **T205**, D4.
 *
 * **The same type in a manifest and on the wire.** A manifest holds it with `{project}` in it; an
 * answer holds it expanded. Nothing else differs, so one type carries both.
 */
export type NextStep = { 
/**
 * What it is.
 */
kind: NextStepKind, 
/**
 * The command, for `once` and `serve`.
 */
run?: string | null, 
/**
 * Where in the site, for `open`; starts with `/`.
 */
path?: string | null, 
/**
 * One sentence shown under the step.
 */
note?: string | null, 
/**
 * The site answers without this step.
 */
optional?: boolean, 
/**
 * This step needs the database account the apply created.
 */
credentials?: boolean, 
/**
 * Which site it belongs to. Absent in schema 1 and 2; T204a defines it.
 */
site?: string | null, };
