// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing a person still has to do after an apply — roadmap task **T205**, D4.
 */
export type NextStepKind = "once" | "serve" | "open";
