// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextStep } from "./NextStep";

/**
 * A project's steps, and whether the blueprint they came from is trusted — T205, D12.
 */
export type NextSteps = { 
/**
 * The blueprint row's own `trusted`.
 */
trusted: boolean, 
/**
 * In order; `{project}` already expanded.
 */
steps: Array<NextStep>, };
