// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What becomes of `from`.
 */
export type OldVersion = { "state": "will_be_removed", } | { "state": "will_be_kept", 
/**
 * One sentence each.
 */
because: Array<string>, } | { "state": "removed", } | { "state": "kept", 
/**
 * One sentence each.
 */
because: Array<string>, };
