// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Execution } from "./Execution";
import type { PackageChannel } from "./PackageChannel";
import type { PackageVersion } from "./PackageVersion";
import type { Requirement } from "./Requirement";

/**
 * One version the index offers, and whether this machine already has it.
 */
export type PackageRelease = { 
/**
 * Which package.
 */
package: string, 
/**
 * Which version.
 */
version: PackageVersion, 
/**
 * Which channel it is published on. Only [`PackageChannel::Stable`] is offered without a
 * setting.
 */
channel: PackageChannel, 
/**
 * Upstream's end of security support, when upstream states one.
 */
eol?: string | null, 
/**
 * How large the download is, so a client can say so before somebody commits to it.
 */
bytes: number, 
/**
 * Whether this exact version is already on this machine.
 */
installed: boolean, 
/**
 * Whether this machine would run that build natively — roadmap task **T92**.
 *
 * Composed by the daemon, which is the only party that knows both what the index published and
 * which triple this build was compiled for. [`None`] means the peer predates the member and
 * never that nothing could be determined, per
 * [ADR 0019](../../../docs/decisions/0019-an-added-response-member-is-optional.md). It is
 * [`Execution::Emulated`] only on an ARM64 Windows machine, where upstream publishes no build
 * of its own for six of the eleven kinds MixEngine offers — PHP among them.
 */
execution?: Execution | null, 
/**
 * What this machine lacks for that build, each with what can be done — roadmap task **T149**.
 *
 * [`None`] means a peer that predates the member, per ADR 0019; an empty list means nothing is
 * lacking or nothing could be judged.
 */
needs?: Array<Requirement> | null, 
/**
 * The line this release belongs to (`8.4`, `22`) — roadmap task **T193a**, D1.
 *
 * Decided by the daemon (`mixengine_core::lines`) so that no client decides it; [`None`] is a
 * daemon that predates the member, per ADR 0019.
 */
line?: string | null, 
/**
 * Whether this is the release its line is represented by: the newest stable one, or the newest
 * pre-release in a line that has no stable release yet. [`None`] as for `line`.
 */
newest_in_line?: boolean | null, };
