// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogueGap } from "./CatalogueGap";
import type { PackageRelease } from "./PackageRelease";
import type { PackageUpdate } from "./PackageUpdate";

/**
 * What `package.list_available` answers.
 *
 * Carries [`stale`](Self::stale) beside the list for
 * [`RuntimeCatalogue`](crate::RuntimeCatalogue)'s reason: a list read from a cache the daemon could
 * not refresh is still a usable list, and a client that showed it without saying so would be
 * claiming the network was reached.
 */
export type PackageCatalogue = { 
/**
 * Every version the index offers **for this machine**, of the packages this build can run.
 */
packages: Array<PackageRelease>, 
/**
 * Whether this came from a cached index the daemon could not refresh.
 */
stale: boolean, 
/**
 * Each installed version whose line has a newer release here, and which one — T193a, D2.
 *
 * Composed with the available list and never with the installed one, because listing what is
 * on the disk must not cost a request to the index. [`None`] is a daemon from before T193.
 */
updates?: Array<PackageUpdate> | null, 
/**
 * What this list could not be read for — roadmap task **T196**.
 *
 * The package index is one file per kind, so one file that could not be read costs that kind
 * and no other. [`None`] is a daemon from before T196; an empty list is one that read
 * everything it was asked for.
 */
unavailable?: Array<CatalogueGap> | null, };
