// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { ServiceId } from "./ServiceId";
import type { Timestamp } from "./Timestamp";

/**
 * One installed package, and what is holding it.
 *
 * One type for the listing and for what an uninstall answers with, on
 * [`RuntimeSummary`](crate::RuntimeSummary)'s precedent: both are the same sentence about a
 * package, so a client renders them with one function.
 */
export type PackageSummary = { 
/**
 * Which package.
 */
package: string, 
/**
 * Which version.
 */
version: PackageVersion, 
/**
 * Where it landed, as a string for display.
 *
 * Not a `PathBuf`, for [`RuntimeSummary`](crate::RuntimeSummary)'s reason: a path is a display
 * value on the wire, and a client that is not on this machine has nothing to open it with.
 */
path: string, 
/**
 * When it was installed.
 */
installed_at: Timestamp, 
/**
 * How much disk it took, as the index declared the archive and the download proved it.
 */
bytes: number, 
/**
 * The services that are instances of this exact version, in [`ServiceId`] order.
 *
 * **What an uninstall refuses over**, and the reason it is on the summary rather than looked up
 * by whoever needs it: `services.package_id` is `ON DELETE RESTRICT`, so a listing that did not
 * say which packages are held would be a listing where "why can I not remove this" has no
 * answer in it. Empty is a package nothing is using.
 */
services: Array<ServiceId>, 
/**
 * Whether the folder this row names is gone — roadmap task **T206d**.
 *
 * `Some(true)` only when the folder answered "not found". A folder that cannot be read for any
 * other reason is not gone, and reads `Some(false)`. `None` is a daemon from before this
 * member (ADR 0019), never "could not tell".
 */
missing?: boolean | null, };
