// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";

/**
 * Which package version to update, and to what.
 */
export type PackageUpgradeQuery = { 
/**
 * Which package.
 */
package: string, 
/**
 * The installed version that moves.
 */
from: PackageVersion, 
/**
 * The release it moves to; absent means the newest of `from`'s line.
 */
to?: PackageVersion | null, };
