// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";

/**
 * `package.upgrade`: the query, and what the person agreed to.
 */
export type PackageUpgrade = { 
/**
 * Keep `from` installed afterwards.
 */
keep?: boolean, 
/**
 * As on `package.install`.
 */
install_prerequisites?: boolean, 
/**
 * As on `package.install`.
 */
ignore_requirements?: boolean, 
/**
 * Raise the elevation prompt for the port grant a new front-end binary needs on Linux, as
 * `service.set_front_end`'s `grant` does. Without it the operation is queued and the update
 * stops with the reason (D6 step 2).
 */
grant?: boolean, 
/**
 * Which package.
 */
package: string, 
/**
 * The installed version that moves.
 */
from: PackageVersion, 
/**
 * The release it moves to; absent means the newest of `from`'s line.
 */
to?: PackageVersion | null, };
