// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { Requirement } from "./Requirement";

/**
 * One installed package version and the newer release of its line — roadmap task **T193a**, D2.
 */
export type PackageUpdate = { 
/**
 * Which package.
 */
package: string, 
/**
 * The installed version.
 */
from: PackageVersion, 
/**
 * The release it would move to.
 */
to: PackageVersion, 
/**
 * Whether `to` is already installed.
 */
to_installed: boolean, 
/**
 * What this machine lacks for `to`.
 */
needs?: Array<Requirement> | null, };
