// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageFound } from "./PackageFound";

/**
 * What `package.found` answers — roadmap task **T182i**.
 */
export type PackageFoundList = { 
/**
 * Every directory with no row, in the order the directory lists them.
 */
found: Array<PackageFound>, };
