// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";
import type { SiteKind } from "./SiteKind";
import type { SiteRoute } from "./SiteRoute";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * One thing an apply would do.
 *
 * **The values a machine assigns at execution time are not here** (D8): the port a new instance
 * lands on, a generated password, a rowid. A plan that named them would be a plan the executor has
 * to contradict.
 */
export type PlanAction = { "action": "register_project", 
/**
 * Its name.
 */
name: string, 
/**
 * Its root.
 */
root: string, 
/**
 * The versions it will ask for — roadmap task **T78**, its design's D7.
 *
 * **Without this the blueprint's `[runtimes]` never reaches the machine**: the new site
 * resolves to whatever this machine defaults to, and a capture of the applied project
 * comes back with no `[runtimes]` at all, because `blueprints::capture` keeps only what
 * `resolve` reports as *not* the default.
 *
 * It is also what makes a version question mean something: an answer of
 * [`MismatchAnswer::UseInstalled`](crate::MismatchAnswer) is a different pin, not just a
 * skipped download.
 */
pins?: { [key in RuntimeKind]?: VersionConstraint }, } | { "action": "install_runtime", 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * What the blueprint asks for.
 *
 * A constraint rather than a version, because the plan reads this home's tables and never
 * the index (D9): a captured blueprint pins one exact version and a hand-written one may
 * pin a range, and which release satisfies a range is a question only the index can answer
 * — at execution time, on the machine doing the installing.
 */
wanted: VersionConstraint, } | { "action": "install_package", 
/**
 * The package: `mariadb`, `redis`.
 */
package: string, 
/**
 * What the blueprint asks for, where it asks for anything.
 *
 * [`None`] takes whatever the index offers newest, decided on the machine doing the
 * installing — [`PlanAction::InstallRuntime`]'s reasoning, and the shape
 * [`PlanAction::EnsureService::version`] already has.
 */
wanted?: VersionConstraint | null, } | { "action": "ensure_service", 
/**
 * The package: `mariadb`, `redis`.
 */
package: string, 
/**
 * The instance name it would be created or found under: `main`, or the project's own.
 */
instance: string, 
/**
 * What the blueprint asks for, where it asks for anything.
 */
version?: VersionConstraint | null, 
/**
 * Whether this instance would belong to the new project alone.
 */
dedicated: boolean, } | { "action": "create_database", 
/**
 * The package whose instance would hold it.
 */
package: string, 
/**
 * Which instance, by the name [`PlanAction::EnsureService`] would have used.
 */
instance: string, 
/**
 * The database name, `{project}` already expanded.
 */
database: string, 
/**
 * The account name, `{project}` already expanded.
 *
 * **Never a password.** The manifest has no key for one, and what an apply generates is
 * not something a plan can name in advance.
 */
user: string, } | { "action": "create_site", 
/**
 * What it serves.
 *
 * A php-fpm pool is not named here even though [`SiteKind::PhpFpm`] can carry one: which
 * pool a new site uses is decided when the site is made, on the machine that makes it.
 */
kind: SiteKind, 
/**
 * Relative to the project root, spelled the way this system spells a path; `""` is the
 * root itself.
 */
doc_root: string, 
/**
 * Whether HTTPS is declared.
 */
https: boolean, 
/**
 * The path routes it declares — roadmap task **T135**.
 *
 * A php-fpm route's pool is not named here, for the reason `kind`'s is: which pool answers
 * is decided on the machine that makes the site. Empty for every blueprint the gallery
 * ships, which is what makes this an addition rather than a change.
 */
routes?: Array<SiteRoute>, } | { "action": "add_domain", 
/**
 * The name, `{project}` already expanded.
 */
domain: string, 
/**
 * Whether it is the primary.
 */
primary: boolean, } | { "action": "issue_certificate", 
/**
 * Every name it would cover.
 */
domains: Array<string>, } | { "action": "set_php_extension", 
/**
 * Which installed PHP the project would run when this plan was made: its pin, or the
 * default where it pins none.
 *
 * [`None`] when no PHP here answers that yet — the plan's own runtime step installs it, and
 * the apply resolves which one it is after that step has run. The apply resolves it in
 * every case rather than trusting this field, so a plan made before an install is never
 * carried out against a PHP that is not there.
 */
runtime?: PackageVersion | null, 
/**
 * The extension's name, as the index spells it.
 */
name: string, } | { "action": "run_scaffold", 
/**
 * The exact command, shown before anything runs it.
 */
command: string, } | { "action": "fetch_archive", 
/**
 * `https://` only; the format comes from its suffix.
 */
url: string, 
/**
 * The archive's single top-level folder whose contents become the project root.
 */
strip?: string | null, } | { "action": "write_dotenv", 
/**
 * The variable name.
 */
key: string, 
/**
 * Relative to the project root: `.env`.
 */
path: string, };
