// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * A copy of an earlier home's state, found in a kept folder.
 */
export type PreviousCopy = { 
/**
 * The copy.
 */
path: string, 
/**
 * When it was written.
 */
taken_at: Timestamp, 
/**
 * Projects it would bring back.
 */
projects: number, 
/**
 * Sites.
 */
sites: number, 
/**
 * Services.
 */
services: number, 
/**
 * Runtimes it names.
 */
runtimes: number, 
/**
 * Packages it names.
 */
packages: number, 
/**
 * Whether a newer MixEngine wrote it, which this build does not restore.
 */
newer: boolean, };
