// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirewallPlan } from "./FirewallPlan";
import type { HostEntry } from "./HostEntry";
import type { PortAccessPlan } from "./PortAccessPlan";
import type { PortAccessTarget } from "./PortAccessTarget";
import type { ResolverPlan } from "./ResolverPlan";
import type { ResolverTarget } from "./ResolverTarget";
import type { TrustPlan } from "./TrustPlan";
import type { TrustTarget } from "./TrustTarget";

/**
 * The closed list of things that cross into the elevated process.
 *
 * See `docs/architecture/platform-abstraction.md`: the list is closed against operations **with
 * effects**, and adding one of those requires an ADR. [`PrivilegedOp::Probe`] has none.
 */
export type PrivilegedOp = { "op": "probe", } | { "op": "hosts-apply", 
/**
 * Sorted and deduplicated by [`PrivilegedOp::hosts_apply`], which is the only way one
 * should be built.
 */
entries: Array<HostEntry>, } | { "op": "port-access-grant", 
/**
 * What to grant, and how — one variant per OS mechanism.
 */
plan: PortAccessPlan, } | { "op": "port-access-revoke", 
/**
 * What to take away.
 */
target: PortAccessTarget, } | { "op": "resolver-apply", 
/**
 * What to route, and how — one variant per OS mechanism.
 */
plan: ResolverPlan, } | { "op": "resolver-revoke", 
/**
 * Which mechanism's artifacts to remove.
 */
target: ResolverTarget, } | { "op": "trust-ca-install", 
/**
 * Which store, and the certificate.
 */
plan: TrustPlan, } | { "op": "trust-ca-remove", 
/**
 * Which authority, by key-id. Never a fingerprint — see [`TrustTarget`].
 */
target: TrustTarget, } | { "op": "firewall-apply", 
/**
 * What should end up open, and under what name.
 */
plan: FirewallPlan, } | { "op": "helper-install", } | { "op": "helper-replace", } | { "op": "helper-remove", } | { "op": "package-remove", } | { "op": "audit-log-remove", };
