// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredSite } from "./DeclaredSite";
import type { ProjectPin } from "./ProjectPin";
import type { ProjectSummary } from "./ProjectSummary";

/**
 * One project and what it actually resolves to.
 */
export type ProjectDetail = { 
/**
 * The project itself.
 */
project: ProjectSummary, 
/**
 * Its pins in **effective** order — the manifest's entry where there is one, the row's where
 * there is not — because that is what the shim will do, and a panel showing anything else is
 * a panel that lies.
 */
pins: Array<ProjectPin>, 
/**
 * The sites its `mixengine.toml` declares, in file order — roadmap task **T204**, spec D7.
 *
 * What lets a client offer the import at all: until T204 only `site.create` read the file,
 * and only at the moment of creating.
 */
declared_sites?: Array<DeclaredSite>, };
