// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `project.export` answers.
 */
export type ProjectExport = { 
/**
 * The file that was written, which is `<root>/mixengine.toml` and nowhere else.
 */
path: string, 
/**
 * Whether the file was made, or an existing one merged into.
 */
created: boolean, 
/**
 * The `domain` of each site entry in the file this home has no site for — roadmap task
 * **T204**, spec D4.
 *
 * Left exactly as written, because an export never deletes; named here, because an entry
 * nobody is told about is a site a colleague will adopt without anyone here having it.
 */
sites_kept?: Array<string>, };
