// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The things this build knows how to take off a machine.
 *
 * **Closed rather than a string**, on [`ProblemId`](crate::ProblemId)'s rule: a client keying off a
 * spelling is a client that silently stops matching, and a row nothing produces does not compile.
 *
 * `Hash` and `Ord` because the daemon keys a map on it while it works through the list, and a test
 * sorts it to prove no two variants share a spelling. Both are free on a fieldless enum.
 */
export type ResidueId = "hosts_block" | "resolver_wiring" | "port_access" | "firewall_rules" | "trust_store" | "browser_trust" | "privileged_helper" | "audit_log" | "package" | "autostart_entry" | "path_entry" | "completed_binary" | "window_data" | "window_cache" | "credentials" | "window_credentials" | "home" | "relocated_directory" | "in_use";
