// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * What answers under a route's path — roadmap task **T135**.
 *
 * [`SiteKind`]'s shape one level down, with the two differences a prefix makes: there is no
 * `node-app`, because a port is an address and a second way to write one is a second thing to keep
 * in step; and `static` carries a root, because mounting a directory at a URL is the whole of what
 * that target says.
 */
export type RouteTarget = { "target": "proxy", 
/**
 * An absolute `http` or `https` URL with a host.
 *
 * **Its path, when it has one, replaces the matched prefix**, trailing slash removed — so
 * `/abc` against `http://127.0.0.1:3003/xyz` reaches `/xyz`, and against
 * `http://127.0.0.1:3003` reaches `/abc`. A query or a fragment is not part of an address.
 */
upstream: string, } | { "target": "php-fpm", 
/**
 * The pool, which the daemon fills from `core::resolve` when a request does not name one.
 *
 * [`None`] means *this route names no pool*, in both directions, for
 * [`SiteKind::PhpFpm`]'s reason.
 */
pool?: ServiceId | null, } | { "target": "static", 
/**
 * Absolute, or relative to the owner's root, spelled the way this system spells a path —
 * [`SiteSummary::doc_root`]'s rule.
 */
root: string, };
