// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";

/**
 * One runtime directory on disk with no row — roadmap task **T182i**. The answer to `runtime.found` is a
 * list of these.
 */
export type RuntimeFound = { 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * Which version the directory is named after.
 */
version: PackageVersion, 
/**
 * The directory.
 */
path: string, 
/**
 * Why it is not recorded yet, as a phrase: no marker (adopting checks it against the package
 * index), a marker for another install, or files missing.
 */
why: string, };
