// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogueGap } from "./CatalogueGap";
import type { RuntimeRelease } from "./RuntimeRelease";
import type { RuntimeUpdate } from "./RuntimeUpdate";

/**
 * What `runtime.list_available` answers.
 *
 * Carries [`stale`](Self::stale) beside the list because the two are one answer: a version list
 * read from a cache the daemon could not refresh is still a usable list, and a client that showed
 * it without saying so would be claiming the network was reached. Why an old index is served at all
 * rather than refused is the index client's decision, not this type's — a tool that can list
 * nothing while the wifi is down is worse than a version list two days old.
 */
export type RuntimeCatalogue = { 
/**
 * Every version the index offers **for this machine** — an artifact listed only for another
 * operating system is not something this one can install, and offering it would turn an absence
 * at list time into a failure at download time.
 */
runtimes: Array<RuntimeRelease>, 
/**
 * Whether this came from a cached index the daemon could not refresh.
 *
 * `false` for a fresh fetch and for a cache still inside its six hours — the distinction a
 * person acts on is "could the publisher be reached", not "how old exactly".
 */
stale: boolean, 
/**
 * Each installed version whose line has a newer release here, and which one — T193a, D2.
 *
 * Composed with the available list and never with the installed one, because listing what is
 * on the disk must not cost a request to the index. [`None`] is a daemon from before T193.
 */
updates?: Array<RuntimeUpdate> | null, 
/**
 * What this list could not be read for — roadmap task **T196**.
 *
 * The package index is one file per kind, so one file that could not be read costs that kind
 * and no other. [`None`] is a daemon from before T196; an empty list is one that read
 * everything it was asked for.
 */
unavailable?: Array<CatalogueGap> | null, };
