// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";

/**
 * `runtime.upgrade`: the query, and what the person agreed to.
 */
export type RuntimeUpgrade = { 
/**
 * Keep `from` installed afterwards.
 */
keep?: boolean, 
/**
 * As on `runtime.install`.
 */
install_prerequisites?: boolean, 
/**
 * As on `runtime.install`.
 */
ignore_requirements?: boolean, 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * The installed version that moves.
 */
from: PackageVersion, 
/**
 * The release it moves to; absent means the newest of `from`'s line.
 */
to?: PackageVersion | null, };
