// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageChannel } from "./PackageChannel";
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";
import type { Timestamp } from "./Timestamp";

/**
 * One installed runtime. The whole of what `runtime.set_default` answers, and what a finished
 * `runtime.install` job carries.
 *
 * One type for the listing, the install's result and the default being moved, on
 * [`ServiceSummary`](crate::ServiceSummary)'s precedent: all three are the same sentence about a
 * runtime, so a client renders them with one function.
 */
export type RuntimeSummary = { 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * Which version.
 */
version: PackageVersion, 
/**
 * Which channel the index published it on.
 */
channel: PackageChannel, 
/**
 * Where it landed, as a string for display.
 *
 * Not a `PathBuf`, for [`DaemonStatus`](crate::DaemonStatus)' reason: a path is a display value
 * on the wire, and a client that is not on this machine — the GUI over the same API — has
 * nothing to open it with.
 */
path: string, 
/**
 * When it was installed.
 */
installed_at: Timestamp, 
/**
 * How much disk it took, as the index declared the archive and the download proved it.
 *
 * The *download* size and not the unpacked one: it is the number the index carries, so
 * reporting it costs nothing, where measuring a tree costs a walk of it on every listing.
 */
bytes: number, 
/**
 * Whether this is the version its kind resolves to when nothing else says otherwise.
 *
 * Exactly one installed version of a kind can carry this — a partial unique index on
 * `runtime_installs` is what makes that true rather than a convention — and a kind can have
 * none, which is what a home is left with when its only version is uninstalled.
 */
default: boolean, 
/**
 * Whether the folder this row names is gone — roadmap task **T206d**.
 *
 * `Some(true)` only when the folder answered "not found". A folder that cannot be read for any
 * other reason is not gone, and reads `Some(false)`. `None` is a daemon from before this
 * member (ADR 0019), never "could not tell".
 */
missing?: boolean | null, };
