// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFound } from "./RuntimeFound";

/**
 * What `runtime.found` answers — roadmap task **T182i**.
 */
export type RuntimeFoundList = { 
/**
 * Every directory with no row, in the order the directory lists them.
 */
found: Array<RuntimeFound>, };
