// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { Requirement } from "./Requirement";
import type { RuntimeKind } from "./RuntimeKind";

/**
 * One installed version and the newer release of its line the index offers — roadmap task
 * **T193a**, D2.
 */
export type RuntimeUpdate = { 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * The installed version.
 */
from: PackageVersion, 
/**
 * The release it would move to.
 */
to: PackageVersion, 
/**
 * Whether `to` is already installed: then nothing is downloaded, and the move still has to be
 * asked for.
 */
to_installed: boolean, 
/**
 * What this machine lacks for `to`, as a release's `needs` says it (T149).
 */
needs?: Array<Requirement> | null, };
