// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agreement to run one command, naming the command.
 *
 * **It names what was read rather than saying yes.** A blueprint can be re-imported between the
 * plan a person read and the apply they sent; a consent naming the command they were shown is the
 * only kind that cannot be spent on a different one.
 */
export type ScaffoldConsent = { 
/**
 * The command as it was shown, `{project}` already expanded. Empty for an archive.
 */
command: string, 
/**
 * The archive URL as it was shown — roadmap task **T205**, D2. Exactly one of `command` and
 * this names what the plan showed.
 */
archive?: string | null, 
/**
 * Whether the person was told this blueprint is nobody's to vouch for.
 *
 * **Checked against the row rather than believed.** A blueprint re-imported without its
 * signature between the reading and the sending would otherwise have its command run under a
 * consent given for a signed one; disagreement in either direction refuses the apply. It is
 * also what keeps the rule in the daemon, where a client cannot decline to hold it.
 */
untrusted: boolean, };
