// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a credential lives in this machine's credential store: the whole address, both halves.
 *
 * **The convention two applications share** — roadmap task **T84**, the design's D6. Until that
 * task a response carried the key alone and the namespace lived inside `mixengine-platform`, so
 * anything outside this workspace that wanted to name the entry — MixLab, or any other graphical client — had
 * to hardcode the word `mixengine`. That second copy is what item 4 of
 * `features/extensions.md`'s *Opening a database in MixLab* list exists to remove.
 *
 * A struct rather than one string with a separator: the two halves are two fields, so there is no
 * separator to pick and nothing to split wrong on the day a key holds the character somebody chose.
 *
 * **Never the password.** An address is a name, which is why it is printed, logged and returned
 * freely while the value it points at is not.
 */
export type SecretAddress = { 
/**
 * The application-side namespace: [`KEYRING_SERVICE`](crate::KEYRING_SERVICE), always.
 */
service: string, 
/**
 * The account within it — `mariadb@main/root`, composed by
 * `mixengine_core::services::handoff::secret_key`.
 */
key: string, };
