// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { ServiceId } from "./ServiceId";

/**
 * One service data directory an earlier home left under `data/`, with no service row — roadmap
 * task **T182g**. The answer to `service.found` is a list of these.
 */
export type ServiceFound = { 
/**
 * The service it would become: what `service.adopt` takes back.
 */
service: ServiceId, 
/**
 * The directory.
 */
path: string, 
/**
 * The server version that bootstrapped it, where its first run finished.
 */
made_by?: PackageVersion | null, 
/**
 * The installed version `service.adopt` would run it with. Absent when it cannot be adopted.
 */
opens_with?: PackageVersion | null, 
/**
 * Why it cannot be adopted yet, as a sentence with what to do. Absent when it can.
 */
why_not?: string | null, };
