// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";
import type { StateReason } from "./StateReason";

/**
 * The service a walk stopped at, and what was persisted about why.
 */
export type ServiceFailure = { 
/**
 * Which service.
 */
service: ServiceId, 
/**
 * What was written about it, which is the same value the matching
 * [`ServiceStateChanged`](crate::DaemonEvent::ServiceStateChanged) carried.
 *
 * [`None`] when the failure was the daemon's own — a database that would not take the write, a
 * supervising task that panicked. That is in `daemon.log` and is not a state a client could
 * render; a client meeting one says so rather than inventing a reason.
 */
reason?: StateReason | null, 
/**
 * What the runner wrote about it — the same sentence `ServiceSummary.last_failure` carries
 * (T200b) — so the first thing a client prints is the runner's and not the state machine's.
 * Roadmap task **T202a**, D3. [`None`] where the reason is, and for a daemon from before it.
 */
detail?: string | null, };
