// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * What `service.adopt` takes — roadmap task **T182g**.
 */
export type ServiceAdopt = { 
/**
 * A service `service.found` listed.
 */
service: ServiceId, };
