// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateReason } from "./StateReason";
import type { Timestamp } from "./Timestamp";

/**
 * One service, as the daemon currently sees it. Also the whole of what `service.status` answers.
 *
 * Why a service last failed — roadmap task **T200b**, its design's D5.
 *
 * `detail` is always a sentence: the error the supervisor had when it gave up, or the reason's
 * own words. That is what lets a client show it without a second table of what each
 * [`StateReason`] means.
 */
export type ServiceFailureNote = { 
/**
 * When it failed.
 */
at: Timestamp, 
/**
 * The reason the transition recorded.
 */
reason: StateReason, 
/**
 * What a person reads.
 */
detail: string, };
