// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceFound } from "./ServiceFound";

/**
 * What `service.found` answers — roadmap task **T182g**.
 */
export type ServiceFoundList = { 
/**
 * Every data directory with no service row, in the order the directory lists them.
 */
found: Array<ServiceFound>, };
