// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { ServiceFailureNote } from "./ServiceFailureNote";
import type { ServiceId } from "./ServiceId";
import type { ServiceRole } from "./ServiceRole";
import type { ServiceState } from "./ServiceState";
import type { StoppedBy } from "./StoppedBy";
import type { Timestamp } from "./Timestamp";

/**
 * One type for the list and for the single lookup on purpose: they are the same sentence about a
 * service, so a client renders them with one function and a field added here reaches both.
 */
export type ServiceSummary = { 
/**
 * Which service this is.
 */
id: ServiceId, 
/**
 * What the `services` row says it is doing.
 *
 * **[`None`] means declared but never created**: something describes how to run this service
 * and the daemon has no row for it, so it has no state to be in and cannot be started until one
 * exists. Not a case a finished MixEngine reaches — from T30 onwards a declaration is *rendered
 * from* a row — which is exactly why it is reported rather than smoothed over into `stopped`: a
 * service that quietly claims to be stopped and then refuses to start explains nothing.
 */
state?: ServiceState | null, 
/**
 * Whether a task in this daemon is supervising it right now.
 *
 * Not a second opinion about [`ServiceSummary::state`] — the row is the only thing that says
 * what a service is doing — but the answer to a different question: a row saying `running` with
 * nothing supervising it is what a daemon that was killed leaves behind, and adopting or
 * clearing those is T18. Until then this is where that gap is visible instead of implied.
 */
supervised: boolean, 
/**
 * The process it is running as, where there is one.
 */
pid: number | null, 
/**
 * The port its row was given, and [`None`] for a service that listens on none.
 *
 * **The number in the row, not one derived from the running process** — roadmap task
 * **T34c**. It is allocated once, when the service is created, and never recomputed: it is in
 * somebody's `.env` and in a colleague's shell history by the end of the afternoon, so a
 * service that quietly moved between restarts would break both. A stopped service has it just
 * as a running one does, which is the point of reporting it here rather than only at creation.
 */
port?: number | null, 
/**
 * When it was last started, whether or not it is still running.
 */
last_started_at: Timestamp | null, 
/**
 * What its process exited with the last time one ended. [`None`] where the OS reported none —
 * a Unix process killed by a signal — for the same reason [`StateReason::Exited`] carries an
 * option there.
 */
last_exit_code: number | null, 
/**
 * What it declares it needs, as the graph holds it: each dependency once, in [`ServiceId`]
 * order. Empty for a service that depends on nothing.
 */
depends_on: Array<ServiceId>, 
/**
 * What this service is *for*, where two packages can be for the same thing — roadmap task
 * **T97**.
 *
 * **The one thing a client could previously do nothing about.** Which program a home's sites
 * are reached through is a fact the daemon holds and never published, so a client wanting to
 * draw it had to hardcode that the package names `caddy` and `nginx` mean "front end" — a copy,
 * in the client, of a table the daemon compiles in. This is that table answering.
 *
 * **A wire fact and not a domain one**, in
 * [ADR 0019](https://github.com/mixnz/mixlab/blob/master/docs/decisions/0019-an-added-response-member-is-optional.md)'s
 * sense: [`None`] means *this daemon was built before the member existed* and never *the role
 * could not be determined*. A row whose package this build has no recipe for is
 * [`ServiceRole::Other`], decided rather than absent — which is the same answer the refusal
 * behind this already gives such a row when it passes over it.
 */
role?: ServiceRole | null, 
/**
 * Whether this service starts when the daemon does — roadmap task **T112**.
 *
 * **The setting and not a prediction**: it says what the column holds, not whether the service
 * will in fact be running after the next login, which depends on a port being free and a
 * program still being there.
 *
 * `false` for a service that is declared and has no row, on the same rule `state` and `port`
 * follow: a service with no row has no setting to report, exactly as it has no state.
 *
 * **Defaulted**, on [ADR 0020]'s rule that the published contract is the shape the daemon
 * writes: a client older than T112 keeps parsing what a newer daemon says, and one newer than
 * a daemon that predates this member reads `false` — which is what every home had before
 * anybody could set it.
 *
 * [ADR 0020]: https://github.com/mixnz/mixlab/blob/master/docs/decisions/0020-the-published-contract-is-the-shape-the-daemon-writes.md
 */
autostart: boolean, 
/**
 * Who left it stopped, while it is — roadmap task **T167d**.
 *
 * **Absent while the service is not `stopped`**, and from a daemon older than this member
 * (ADR 0019). It is what lets a client tell a service MixEngine put to rest, which the next
 * request wakes, from one a person stopped — which stays stopped — and draw the first as
 * resting rather than as a failure ([ADR 0041]).
 *
 * [ADR 0041]: https://github.com/mixnz/mixlab/blob/master/docs/decisions/0041-mixengine-stops-nothing-a-person-did-not-ask-it-to.md
 */
stopped_by?: StoppedBy | null, 
/**
 * Which version of its program this service runs — roadmap task **T183**.
 *
 * **What a person reads next to the id**, because the id is a name they chose and says
 * nothing about the program: `mysql@main` is whichever MySQL was installed when it was created.
 * The full version as installed; a client that wants the `5.7` line drops the rest itself.
 *
 * [`None`] is drawn as nothing, whichever of its causes it has: a daemon from before this
 * member (ADR 0019), a declared service with no row, an extension's service, or a stored text
 * this build cannot parse.
 */
version?: PackageVersion | null, 
/**
 * Why it failed, while it is `failed` — roadmap task **T200b**, D5.
 *
 * On `stopped_by`'s rule: the row keeps the note after a person stops a failed service, and no
 * listing shows a failure the state no longer claims. Optional on the wire (ADR 0019).
 */
last_failure?: ServiceFailureNote | null, };
