// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * One path prefix on a site, and what answers it — roadmap task **T135**.
 *
 * **Beside [`SiteKind`] rather than inside it.** A site is a kind plus an ordered set of these, and
 * the kind is what answers everything no route matched — which is why `/` is not a path a route may
 * take: what answers `/` is the kind, and a second answer to a question that has one is a state
 * nothing should be able to spell.
 */
export type SiteRoute = { 
/**
 * An absolute path prefix, matched at segment boundaries: `/api` takes `/api` and `/api/x`, and
 * never `/apidocs`.
 */
path: string, } & ({ "target": "proxy", 
/**
 * An absolute `http` or `https` URL with a host.
 *
 * **Its path, when it has one, replaces the matched prefix**, trailing slash removed — so
 * `/abc` against `http://127.0.0.1:3003/xyz` reaches `/xyz`, and against
 * `http://127.0.0.1:3003` reaches `/abc`. A query or a fragment is not part of an address.
 */
upstream: string, } | { "target": "php-fpm", 
/**
 * The pool, which the daemon fills from `core::resolve` when a request does not name one.
 *
 * [`None`] means *this route names no pool*, in both directions, for
 * [`SiteKind::PhpFpm`]'s reason.
 */
pool?: ServiceId | null, } | { "target": "static", 
/**
 * Absolute, or relative to the owner's root, spelled the way this system spells a path —
 * [`SiteSummary::doc_root`]'s rule.
 */
root: string, });
