// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteKind } from "./SiteKind";
import type { SiteOwner } from "./SiteOwner";
import type { SiteRoute } from "./SiteRoute";
import type { SiteSharing } from "./SiteSharing";
import type { SiteState } from "./SiteState";

/**
 * One site, as a listing shows it.
 */
export type SiteSummary = { 
/**
 * Its primary domain, which is also how it is addressed.
 */
domain: string, 
/**
 * Who it belongs to.
 */
owner: SiteOwner, 
/**
 * What it serves.
 */
kind: SiteKind, 
/**
 * Relative to the project's root, spelled the way this system spells a path. `""` is the
 * root itself.
 */
doc_root: string, 
/**
 * Whether HTTPS is declared.
 */
https: boolean, 
/**
 * Whether the plaintext address redirects to the HTTPS one — roadmap task **T98**.
 */
https_redirect: boolean, 
/**
 * Whether the web server should serve it.
 */
state: SiteState, 
/**
 * Every route, **in match order** — longest path first — roadmap task **T135**.
 *
 * **On the summary and not only on the detail**, on [`sharing`](Self::sharing)'s argument: what
 * is behind a site is a question about every site at once, and a list that could not answer it
 * would make a client ask per row.
 *
 * Not the order somebody typed: overlaps are resolved by specificity where the configuration is
 * rendered, so a listing showing declaration order would be showing something the front end
 * does not do. Optional on the wire,
 * [ADR 0019](../../../docs/decisions/0019-an-added-response-member-is-optional.md).
 */
routes?: Array<SiteRoute>, 
/**
 * Where the local network can reach it, when it can — roadmap task **T74**.
 *
 * **On the summary and not only on the detail**, because "what is exposed right now" is a
 * question about every site at once: a list that could not answer it would make a client ask
 * per site, and the one thing a person wants at a glance is whether *anything* is shared.
 */
sharing?: SiteSharing | null, };
