// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRef } from "./ProjectRef";
import type { ServiceId } from "./ServiceId";
import type { SiteKind } from "./SiteKind";
import type { SiteRoute } from "./SiteRoute";

/**
 * Create a site under a project.
 *
 * Every field but the project falls through — the argument, then `[site]` in the project's
 * manifest, then a default — which is what makes `site.create { project }` the import (spec D7),
 * and `site.create { project, from }` the import of one of several (roadmap task **T204**).
 */
export type SiteCreate = { 
/**
 * Which project it belongs to.
 */
project: ProjectRef, 
/**
 * Which of the manifest's sites to fall through to, by any of its names — roadmap task
 * **T204**, spec D5. Needed when the file declares more than one and the request names no
 * domain that picks one.
 */
from?: string | null, 
/**
 * Ordered; the head is the primary. Falls through to `[site] domain` + `aliases`, then to
 * `<slug>.test`.
 */
domains?: Array<string> | null, 
/**
 * Absolute, or relative to the root. Falls through to `[site] doc_root`, then to the root.
 */
doc_root?: string | null, 
/**
 * Falls through to `[site]`, then to php-fpm with the resolved pool.
 */
kind?: SiteKind | null, 
/**
 * The services it declares. Falls through to `[[services]]`, then to none.
 */
services?: Array<ServiceId> | null, 
/**
 * The routes it declares, **replacing** the list rather than merging into it — roadmap task
 * **T135**. Falls through to `[[site.routes]]`, then to none.
 */
routes?: Array<SiteRoute> | null, 
/**
 * Whether HTTPS is wanted. A declaration Phase 5 reads; nothing today acts on it.
 */
https?: boolean | null, 
/**
 * Whether the plaintext address should redirect to the HTTPS one — roadmap task **T98**.
 *
 * Refused when `true` beside an `https` that resolves to `false`, whether that is this same
 * request's own `https: Some(false)` or a `https` left unset on a site created plaintext-only.
 */
https_redirect?: boolean | null, 
/**
 * `.local`, acknowledged. `--i-know` on the CLI.
 */
accept_risky_tld?: boolean, };
