// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * One thing an update moves, keeps or says — D5, D6, D7.
 */
export type UpgradeItem = { "item": "site", 
/**
 * Its primary domain.
 */
site: string, 
/**
 * The pool it points at now.
 */
from: ServiceId, 
/**
 * The pool it will point at.
 */
to: ServiceId, } | { "item": "extension_pool", 
/**
 * The pool.
 */
pool: ServiceId, 
/**
 * Whether it moves.
 */
moves: boolean, 
/**
 * What its manifest requires, where it could be read.
 */
requires?: VersionConstraint | null, } | { "item": "dropped_extension", 
/**
 * The extension.
 */
name: string, } | { "item": "pin", 
/**
 * The project.
 */
project: string, 
/**
 * The pin as it is.
 */
from: VersionConstraint, 
/**
 * The pin as it will be.
 */
to: VersionConstraint, } | { "item": "manifest", 
/**
 * The project.
 */
project: string, 
/**
 * The file.
 */
path: string, 
/**
 * What it pins.
 */
constraint: VersionConstraint, } | { "item": "tool", 
/**
 * The command.
 */
name: string, } | { "item": "default", } | { "item": "instance", 
/**
 * The instance.
 */
service: ServiceId, 
/**
 * Whether it is stopped and started again for it.
 */
restarts: boolean, } | { "item": "front_end_restart", 
/**
 * The front end.
 */
service: ServiceId, } | { "item": "no_downgrade", 
/**
 * The instance.
 */
service: ServiceId, };
