// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one entry went. Every entry of a plan is `planned`; a finished job's are the rest.
 */
export type UpgradeOutcome = { "outcome": "planned", } | { "outcome": "done", } | { "outcome": "skipped", } | { "outcome": "failed", 
/**
 * Why, in a sentence.
 */
because: string, };
