// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OldVersion } from "./OldVersion";
import type { PackageVersion } from "./PackageVersion";
import type { Requirement } from "./Requirement";
import type { UpgradeEntry } from "./UpgradeEntry";

/**
 * What an update will do (`*.upgrade_plan`) or did (the job's result) — D7.
 */
export type UpgradePlan = { 
/**
 * The runtime kind or package name.
 */
subject: string, 
/**
 * The installed version that moves.
 */
from: PackageVersion, 
/**
 * The release it moves to.
 */
to: PackageVersion, 
/**
 * Whether `to` was already installed, so nothing is downloaded.
 */
to_installed: boolean, 
/**
 * The download, in bytes; `0` when `to_installed`.
 */
bytes: number, 
/**
 * Whether the index this was judged against is a stale cached copy.
 */
stale: boolean, 
/**
 * What this machine lacks for `to`.
 */
needs: Array<Requirement>, 
/**
 * Everything that moves, is kept or is said.
 */
entries: Array<UpgradeEntry>, 
/**
 * What becomes of `from`.
 */
old: OldVersion, };
