// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpgradeItem } from "./UpgradeItem";
import type { UpgradeOutcome } from "./UpgradeOutcome";

/**
 * One entry of a plan.
 */
export type UpgradeEntry = { 
/**
 * What.
 */
item: UpgradeItem, 
/**
 * How it went.
 */
outcome: UpgradeOutcome, };
